### ISSUE TITLE
Installation Lab

### ISSUE THREAD

**Issue by amit-agilitics** [amit-agilitics/SEBC#2]
**Installation of CM / CDH / MYSQL on AWS**

1. Logged into AWS with login credentials
2. Created 5 instances of CentOS 6.5 M3.Xlarge
3. Changed the default size to 30 GB
4. Changed the Storage type of SSD
5.  renamed the newly launched server... 1 Edge+CM, 1 Master, 3 Slaves
6. written name and IP to the files
7. Connected to all the 5 server using PEM file.
8. Checked pre-requisite (IPV6 disable, reverse lookup, NTPD, SElinux Disabled)

> 
> The Report about the System's Swappiness, IP tables, name resolution and no. of cores in the system
> ___________________________________________________________________________________________________
> 
> The current swappiness of the system is 
> 1
> 
> ************************************************
> 
> The hostname for a given IP address
> ./script: line 21: dig: command not found
> Hostname does not exists
> 
> ************************************************
> 
> The IP address for a given hostname is
> ./script: line 32: host: command not found
> ************************************************
> 
> The current status of the IP tables service is 
> Table: filter
> Chain INPUT (policy ACCEPT)
> num  target     prot opt source               destination         
> 1    ACCEPT     all  --  0.0.0.0/0            0.0.0.0/0           state RELATED,ESTABLISHED 
> 2    ACCEPT     icmp --  0.0.0.0/0            0.0.0.0/0           
> 3    ACCEPT     all  --  0.0.0.0/0            0.0.0.0/0           
> 4    ACCEPT     tcp  --  0.0.0.0/0            0.0.0.0/0           state NEW tcp dpt:22 
> 5    REJECT     all  --  0.0.0.0/0            0.0.0.0/0           reject-with icmp-host-prohibited 
> 
> Chain FORWARD (policy ACCEPT)
> num  target     prot opt source               destination         
> 1    REJECT     all  --  0.0.0.0/0            0.0.0.0/0           reject-with icmp-host-prohibited 
> 
> Chain OUTPUT (policy ACCEPT)
> num  target     prot opt source               destination         
> 
> 
> ************************************************
> 
> To test if the Firewall software status (on/off)
> iptables       	0:off	1:off	2:on	3:on	4:on	5:on	6:off
> 
> Now for IPv6
> ip6tables      	0:off	1:off	2:on	3:on	4:on	5:on	6:off
> 
> ************************************************
> 
> The number of cores available in the system are 
> 4
>

**Comment by mfernest** [comment]
Looks good so far.

**Comment by amit-agilitics** [comment]
Installation completed after lot of struggle...Image has been updated.
The basic issue was in my sql and as well version of SQL's that was fixed after struggle

**Comment by mfernest** [comment]
Several required files in `installation/labs` have not been updated.

INC
