### ISSUE TITLE
Install MySQL

### ISSUE THREAD

**Issue by amit-agilitics** [amit-agilitics/SEBC#3]

**Comment by amit-agilitics** [comment]
Initial Version

**Comment by bomb-magnet** [comment]
I found this entry puzzling:
```
create database metastore DEFAULT CHARACTER SET utf8;
grant all on metastore.* to 'hue'@'%' IDENTIFIED BY 'hue';
```

What was your rationale for this store and it's user permissions?

**Comment by bomb-magnet** [comment]
Generally the formatting could be a little easier to follow. The point is less about my formatting requirements and more about making these notes easy to refer to, should you need them in the future.

**C**omplete.
